#!/usr/bin/env bash
#idisplay Fizzbuzz Fizz Buzz message
c=1
for i in $(seq 1 100);
do
	if [ $((c%15)) -eq 0 ]
	then
		echo "FizzBuzz"
	
	elif [ $((c%3)) -eq 0 ]
       	then
		echo "Fizz"
	
	elif [ $((c%5)) -eq 0 ] 
	then
		echo "Buzz"
	
	else
		echo "$c"
	fi
done

	
