#!/usr/bin/env bash
#display the time for 12 hoursm 59 minutes
m=0
h=0
while [ $h -lt 13 ]
do
       echo "$h"
       h= $(($h + 1)) 
       while [ $m -lt 60 ]
       do
	       echo "$m"
	       m= $(($m + 1))
       done
done



