#!/usr/bin/env bash
#display the time for 12 hoursm 59 minutes
m=0

while [ $m -lt 60 ]
do
       echo "$m"
       ((m++)) 
       while [ $m -lt 13 ]
       do
	       echo "hours:$m"
	       ((m++))
       done
done



