#!/usr/bin/env bash
#display the time for 12 hoursm 59 minutes
hour=0

while [ $hour -le 60 ]
do
       echo "$hour:"$hour
       ((m++)) 
       while [ $hour -lt 13 ]
       do
	       echo "$hour"
	       ((m++))
       done
done



