#!/usr/bin/env bash
# give info about file school
if [ -f $"File" ]; then
	echo $"school file exists"
	if 
		echo $"school file does not exists"
		if [ -s $"File"]; then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
	fi
fi

