#!/usr/bin/env bash
# give info about file school
File=school 

if [ -e "$File" ]; then
	echo $"school file exists"

	if [ -s "$File" ]; then
	echo $"school file is not empty"
	
	if [ $"$File" ]; then
	echo "school file exist but empty"
	fi

	if [ -f "$file" ]; then		
	echo "school file is a regular file"
	fi 
else
       echo "school file doesn't exist"	

fi



