#!/usr/bin/env bash
# give info about file school
File=school 

if [ -e "$File" ]; then
	echo $"school file exists"

	if [ -s "$File" ]; then
	echo $"school file does not exists"

	else
	echo "school file is  empty"
	fi

	if [ -f "$file" ]		
	echo "school file is a regular file"
	fi 
else
       echo "holbertonschool file does not exist"	

fi



