#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

#create a file
sudo touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid #echo the pid

# infinite while loop

while ( true )                                                                                                                                      
do                                                                                               
	echo "To infinity and beyound"
	sleep 2

	# Trap-Conditions + arguments

	trap "echo Y U no love me ?!"  SIGTINT
	trap "echo I hate the kill command" SIGTERM 
	trap "echo I hate the kill command" exit SIGQUIT #exit condition
done
