#!/usr/bin/env bash                                                                                                                           
#kill_previous task without kill command                                                                                                      
kill -SIGTERM 7510   
