#!/usr/bin/env bash                                                                                                                           
#kill_previous task without kill command                                                                                                      
pkill -f 5170  
